name: Playwright Tests
on:
  push:
    branches: [ main, master, feature/cucumber-report ]
  pull_request:
    branches: [ main, master, feature/cucumber-report ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/cucumber-reports.html

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./report

      - name: Checkout gh-report-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-report-pages
          token: ${{ secrets.PAT }}

      - name: Copy report to gh-report-pages branch
        run: |
          mkdir -p report
          cp target/cucumber-reports.html report/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add report/cucumber-reports.html
          git commit -m 'Deploy Cucumber Report'
          git push origin gh-report-pages



