name: Playwright Tests
on:
  push:
    branches: [ main, master, feature/cucumber-report ]
  pull_request:
    branches: [ main, master, feature/cucumber-report ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/cucumber-reports.html

      - name: List target directory contents
        run: ls -la target

      - name: Deploy cucumber report to gh-report-pages branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
          git checkout --orphan gh-report-pages
          
          git rm -rf .
          cp -r target/cucumber-reports.html .
          
          # Commit and push the changes
          git add target/cucumber-reports.html
          git commit -m "Deploy Cucumber report"
          git push --force origin gh-report-pages